{application,erl_playground,
             [{description,"A safe playground for all your dirty stuff"},
              {vsn,"1.0.0"},
              {registered,[]},
              {mod,{erl_playground_app,[]}},
              {applications,[kernel,stdlib,lager,recon]},
              {env,[]},
              {modules,[erl_playground_app,erl_playground_pb,
                        erl_playground_sup,node_boot,sockclient,sockserv,
                        utils]}]}.
